"""add is_hidden to categories

Revision ID: 10419e48aa35
Revises: 1b9172660ada
Create Date: 2026-03-31 18:18:49.364621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10419e48aa35'
down_revision: Union[str, Sequence[str], None] = '1b9172660ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_hidden')
    # ### end Alembic commands ###
