"""add notes to budgets, schedule_type and transfer fields to schedules

Revision ID: 3b688648a253
Revises: 052a44b30279
Create Date: 2026-04-14 17:47:39.015061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b688648a253'
down_revision: Union[str, Sequence[str], None] = '052a44b30279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('schedule_type', sa.String(length=20), server_default='regular', nullable=False))
    op.add_column('schedules', sa.Column('from_account_id', sa.Uuid(as_uuid=True), nullable=True))
    op.add_column('schedules', sa.Column('to_account_id', sa.Uuid(as_uuid=True), nullable=True))
    op.alter_column('schedules', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_schedules_to_account_id_accounts', 'schedules', 'accounts', ['to_account_id'], ['id'])
    op.create_foreign_key('fk_schedules_from_account_id_accounts', 'schedules', 'accounts', ['from_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_schedules_from_account_id_accounts', 'schedules', type_='foreignkey')
    op.drop_constraint('fk_schedules_to_account_id_accounts', 'schedules', type_='foreignkey')
    op.alter_column('schedules', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('schedules', 'to_account_id')
    op.drop_column('schedules', 'from_account_id')
    op.drop_column('schedules', 'schedule_type')
    op.drop_column('budgets', 'notes')
    # ### end Alembic commands ###
