"""create reallocations table

Revision ID: 811ad478268a
Revises: fa4ac619d396
Create Date: 2026-04-03 21:18:26.203983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811ad478268a'
down_revision: Union[str, Sequence[str], None] = 'fa4ac619d396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reallocations',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('from_category_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('to_category_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['to_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reallocations_user_id'), 'reallocations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reallocations_user_id'), table_name='reallocations')
    op.drop_table('reallocations')
    # ### end Alembic commands ###
