"""add promotions table and promotion_id to transactions

Revision ID: 9c897e2d3a1b
Revises: ccd395e45b3a
Create Date: 2026-04-11 19:36:57.289490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c897e2d3a1b'
down_revision: Union[str, Sequence[str], None] = 'ccd395e45b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('account_id', sa.Uuid(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('promotion_type', sa.String(length=20), nullable=False),
    sa.Column('original_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_monthly_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_user_id'), 'promotions', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('promotion_id', sa.Uuid(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_transactions_promotion_id_promotions', 'transactions', 'promotions', ['promotion_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_promotion_id_promotions', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'promotion_id')
    op.drop_index(op.f('ix_promotions_user_id'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
