"""add group_opening_balances table

Revision ID: cd423bd46369
Revises: e7c70033d4f5
Create Date: 2026-04-13 16:56:26.991457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd423bd46369'
down_revision: Union[str, Sequence[str], None] = 'e7c70033d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_opening_balances',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group', 'year', name='uq_opening_balance_user_group_year')
    )
    op.create_index(op.f('ix_group_opening_balances_user_id'), 'group_opening_balances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_opening_balances_user_id'), table_name='group_opening_balances')
    op.drop_table('group_opening_balances')
    # ### end Alembic commands ###
