"""nullable category_id on transactions, add group to schedules

Revision ID: e7c70033d4f5
Revises: 9c897e2d3a1b
Create Date: 2026-04-12 19:01:59.232247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c70033d4f5'
down_revision: Union[str, Sequence[str], None] = '9c897e2d3a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('group', sa.String(length=50), nullable=True))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('schedules', 'group')
    # ### end Alembic commands ###
